---
#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-web-green
  type: ClusterIP