apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-centos
  namespace: default
  labels:
    k8s-app: daemon-centos
spec:
  selector:
    matchLabels:
      name: daemon-centos
  template:
    metadata:
      labels:
        name: daemon-centos
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: centos-svc
        image: registry.cn-beijing.aliyuncs.com/alexzhang/centos-full
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: configs
              key: JAVA_OPTS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: configs
              key: LOG_LEVEL
        - name: HTTP_PORT
          value: "9987"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  JAVA_OPTS: -Xms1024m
  LOG_LEVEL: DEBUG