# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deploy-head
spec:
  selector:
    matchLabels:
      app: centos-head
  replicas: 1
  template:
    metadata:
      labels:
        app: centos-head
    spec:
      containers:
      - name: centos
        image: registry.cn-beijing.aliyuncs.com/alexzhang/centos-full
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]