#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-eureka-gfs-deploy
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: spring-eureka-gfs
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-eureka-gfs
    spec:
      containers:
      - name: spring-eureka-gfs
        image: registry.cn-beijing.aliyuncs.com/alexzhang/spring-eureka:2.0.0
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: gluster-volume
            mountPath: "/gfs-data"
            readOnly: false
      volumes:
      - name: gluster-volume
        persistentVolumeClaim:
          claimName: glusterfs-pvc
