apiVersion: v1
kind: Pod
metadata:
   name: eureka
   labels:
     name: eureka-pod
spec:
   containers:
   - name: eureka
     image: registry.cn-beijing.aliyuncs.com/alexzhang/spring-eureka:2.0.0
     ports:
     - containerPort: 8080
       hostPort: 8080