#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-eureka-dep-public
spec:
  selector:
    matchLabels:
      app: springboot-eureka-public
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-eureka-public
    spec:
      containers:
      - name: springboot-eureka-public
        image: registry.cn-beijing.aliyuncs.com/alexzhang/spring-eureka:2.0.0
        ports:
        - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-eureka-service-public
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-eureka-public
  type: ClusterIP

---
#ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springboot-eureka-ingress
spec:
  rules:
  - host: eureka.kaikeba.com
    http:
      paths:
      - path: /
        backend:
          serviceName: springboot-eureka-service-public
          servicePort: 80