apiVersion: v1
kind: Pod
metadata:
   namespace: eureka
   name: spring-web-pod-ns
   labels:
     name: spring-web-pod-ns
spec:
   #hostNetwork: true
   #hostPID: true
   hostAliases:
   - ip: "123.11.1.1"
     hostnames:
     - "dns.kaikeba.com"
   containers:
   - name: centos-pod-ns
     image: registry.cn-beijing.aliyuncs.com/alexzhang/centos-full
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo hello; sleep 10;done"]