#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-eureka-hpa
spec:
  selector:
    matchLabels:
      app: springboot-eureka-hpa
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-eureka-hpa
    spec:
      containers:
      - name: springboot-eureka-hpa
        image: registry.cn-beijing.aliyuncs.com/alexzhang/centos-full
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 3
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-eureka-hpa
  labels:
    app: springboot-eureka-hpa
    version: v2beta1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-eureka-hpa
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50