apiVersion: v1
kind: Service
metadata:
  name: centos-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: centos-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deploy-head
spec:
  serviceName: "centos-service"
  selector:
    matchLabels:
      app: centos-head
  replicas: 3
  template:
    metadata:
      labels:
        app: centos-head
    spec:
      containers:
      - name: centos
        image: registry.cn-beijing.aliyuncs.com/alexzhang/centos-full
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]